# Generated by Django 3.1.2 on 2020-11-20 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabellingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
                ('human_name', models.CharField(max_length=256)),
                ('order_key', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels_json_str', models.TextField(default='[]')),
                ('creation_date', models.DateField()),
                ('edit_time_elapsed', models.FloatField(blank=True, default=0.0)),
                ('last_modified_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('lock_expiry_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('completed_tasks', models.ManyToManyField(to='image_labelling_tool.LabellingTask')),
                ('last_modified_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_labels', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_labels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
