# Generated by Django 3.1.7 on 2021-03-17 11:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('image_labelling_tool', '0006_remove_labels_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('[a-zA-Z_][a-zA-Z0-9_]*'), message='Enter a valid identifier (letters or underscore, followedby letters, numbers or underscore')], verbose_name='Species identifier name')),
                ('human_name', models.CharField(default='', max_length=64)),
                ('default_colour', models.CharField(default='#0080ff', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('order_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LabelClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.CharField(default='', max_length=64, verbose_name='Name of label class group as shown in UI')),
                ('active', models.BooleanField(default=True)),
                ('order_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LabellingColourScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('[a-zA-Z_][a-zA-Z0-9_]*'), message='Enter a valid identifier (letters or underscore, followedby letters, numbers or underscore')], verbose_name='Colour scheme identifier name')),
                ('human_name', models.CharField(default='', max_length=64, verbose_name='Name of colour scheme as shown in UI')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelClassColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(default='#0080ff', max_length=8)),
                ('label_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_colours', to='image_labelling_tool.labelclass')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_colours', to='image_labelling_tool.labellingcolourscheme')),
            ],
        ),
        migrations.AddField(
            model_name='labelclass',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_classes', to='image_labelling_tool.labelclassgroup'),
        ),
    ]
