# Generated by Django 3.1.2 on 2020-11-20 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_labelling_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('labels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='image_labelling_tool.labels')),
            ],
        ),
        migrations.CreateModel(
            name='DextrTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_id_str', models.CharField(max_length=128)),
                ('dextr_id', models.IntegerField()),
                ('celery_task_id', models.CharField(max_length=128)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_labeller.imagewithlabels')),
            ],
        ),
    ]
